### ISSUE TITLE
Where can We find video clips itself?

### ISSUE THREAD

**Issue by kyoto7250** [ku-nlp/VISA#1]
Hello, Thank you for your dataset.

`I3D` and `RCNN` features are listed in `README.md` and can be downloaded, but where can I get the video clips itself?

From the annotations in the paper, does this mean we need to send an email to confirm the dataset?

Best regards.

**Comment by cromz22** [comment]
Hi, thank you for showing interest in our work.
We cannot make the video clips publicly available because of the copyright issue.
Please contact liyh@nlp.ist.i.kyoto-u.ac.jp if you need them.

**Comment by kyoto7250** [comment]
Thank you for quick reply.

I will close this PR :)
